recipe-list:
    path: /api/v1/recipes
    methods:
      - GET
    controller: App\Controller\RecipeRestfulController:getRecipesAction

recipe-list-future:
    path: /api/v1/recipes
    methods:
      - PUT
      - DELETE
      - POST
      - OPTIONS
    controller: App\Controller\RecipeRestfulController:notImplementedAction